type ColorCollection = {
  [key: string]: string;
}

export const colors: ColorCollection = {
  "ледяной голубой": "aliceblue",
  "античный белый": "antiquewhite",
  "аква": "aqua",
  "аквамарин": "aquamarine",
  "лазурный": "azure",
  "бежевый": "beige",
  "бисквитный": "bisque",
  "черный": "black",
  "светло-миндальный": "blanchedalmond",
  "синий": "blue",
  "сине-фиолетовый": "blueviolet",
  "коричневый": "brown",
  "светло-коричневый": "burlywood",
  "военно-воздушный": "cadetblue",
  "зеленовато-желтый": "chartreuse",
  "шоколадный": "chocolate",
  "коралловый": "coral",
  "васильковый": "cornflowerblue",
  "кукурузный": "cornsilk",
  "малиновый": "crimson",
  "циан": "cyan",
  "темно-синий": "darkblue",
  "темный циан": "darkcyan",
  "темный золотистый": "darkgoldenrod",
  "темно-серый": "darkgray",
  "темно-зеленый": "darkgreen",
  "темно-хаки": "darkkhaki",
  "темный пурпурный": "darkmagenta",
  "темно-оливковый": "darkolivegreen",
  "темно-оранжевый": "darkorange",
  "темный орхидейный": "darkorchid",
  "темно-красный": "darkred",
  "темный лососевый": "darksalmon",
  "темный морской волны": "darkseagreen",
  "темный грифельный": "darkslategray",
  "темный бирюзовый": "darkturquoise",
  "темно-фиолетовый": "darkviolet",
  "темно-розовый": "deeppink",
  "ярко-голубой": "deepskyblue",
  "тускло-серый": "dimgray",
  "бледно-синий": "dodgerblue",
  "кирпичный": "firebrick",
  "цветочно-белый": "floralwhite",
  "зеленый лес": "forestgreen",
  "фуксия": "fuchsia",
  "геинсборо": "gainsboro",
  "призрачно-белый": "ghostwhite",
  "золотой": "gold",
  "золотистый": "goldenrod",
  "серый": "gray",
  "зеленый": "green",
  "желто-зеленый": "greenyellow",
  "медовый": "honeydew",
  "ярко-розовый": "hotpink",
  "индийский красный": "indianred",
  "индиго": "indigo",
  "слоновой кости": "ivory",
  "хаки": "khaki",
  "лавандовый": "lavender",
  "розовато-лавандовый": "lavenderblush",
  "зеленая лужайка": "lawngreen",
  "белый с лимонным оттенком": "lemonchiffon",
  "светло-голубой": "lightblue",
  "светло-коралловый": "lightcoral",
  "светло-циановый": "lightcyan",
  "светло-желто-золотистый": "lightgoldenrodyellow",
  "светло-серый": "lightgray",
  "светло-зеленый": "lightgreen",
  "светло-розовый": "lightpink",
  "светлый лососевый": "lightsalmon",
  "светлый морской волны": "lightseagreen",
  "светлый небесно-голубой": "lightskyblue",
  "светлый грифельный": "lightslategray",
  "светлый стальной": "lightsteelblue",
  "светло-желтый": "lightyellow",
  "лайм": "lime",
  "зеленый лайм": "limegreen",
  "льняной": "linen",
  "пурпурный": "magenta",
  "темно-бордовый": "maroon",
  "средний аквамарин": "mediumaquamarine",
  "средний синий": "mediumblue",
  "средний орхидейный": "mediumorchid",
  "средний фиолетовый": "mediumpurple",
  "средний морской волны": "mediumseagreen",
  "средний грифельный": "mediumslateblue",
  "средний весенне-зеленый": "mediumspringgreen",
  "средний бирюзовый": "mediumturquoise",
  "средний пурпурно-красный": "mediumvioletred",
  "темно-ночной": "midnightblue",
  "мятный крем": "mintcream",
  "туманно-розовый": "mistyrose",
  "мокасин": "moccasin",
  "белый навахо": "navajowhite",
  "старая кружевная": "oldlace",
  "оливковый": "olive",
  "зелено-оливковый": "olivedrab",
  "оранжевый": "orange",
  "оранжево-красный": "orangered",
  "орхидейный": "orchid",
  "бледно-золотистый": "palegoldenrod",
  "бледно-зеленый": "palegreen",
  "бледно-бирюзовый": "paleturquoise",
  "бледно-фиолетово-красный": "palevioletred",
  "папайя": "papayawhip",
  "персиковый": "peachpuff",
  "перуанский": "peru",
  "розовый": "pink",
  "сливовый": "plum",
  "пудрово-голубой": "powderblue",
  "фиолетовый": "purple",
  "красный": "red",
  "розово-коричневый": "rosybrown",
  "королевский синий": "royalblue",
  "кожано-коричневый": "saddlebrown",
  "лососевый": "salmon",
  "песочный коричневый": "sandybrown",
  "морской волны": "seagreen",
  "морская раковина": "seashell",
  "охра": "sienna",
  "серебряный": "silver",
  "небесно-голубой": "skyblue",
  "грифельно-синий": "slateblue",
  "грифельно-серый": "slategray",
  "снежный": "snow",
  "весенне-зеленый": "springgreen",
  "стальной": "steelblue",
  "желто-коричневый": "tan",
  "чирок": "teal",
  "чертополох": "thistle",
  "томатный": "tomato",
  "бирюзовый": "turquoise",
  "пшеничный": "wheat",
  "белый": "white",
  "дымчато-белый": "whitesmoke",
  "желтый": "yellow",
};
